#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBanking.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EBanking")]
	public partial class EBankingDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCuenta(Cuenta instance);
    partial void UpdateCuenta(Cuenta instance);
    partial void DeleteCuenta(Cuenta instance);
    partial void InsertTipoCuenta(TipoCuenta instance);
    partial void UpdateTipoCuenta(TipoCuenta instance);
    partial void DeleteTipoCuenta(TipoCuenta instance);
    partial void InsertTransferencia(Transferencia instance);
    partial void UpdateTransferencia(Transferencia instance);
    partial void DeleteTransferencia(Transferencia instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    #endregion
		
		public EBankingDataDataContext() : 
				base(global::EBanking.DAL.Properties.Settings.Default.EBankingConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EBankingDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EBankingDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EBankingDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EBankingDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cuenta> Cuentas
		{
			get
			{
				return this.GetTable<Cuenta>();
			}
		}
		
		public System.Data.Linq.Table<TipoCuenta> TipoCuentas
		{
			get
			{
				return this.GetTable<TipoCuenta>();
			}
		}
		
		public System.Data.Linq.Table<Transferencia> Transferencias
		{
			get
			{
				return this.GetTable<Transferencia>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Transferencias_SEL_ALL_BYCuentaIdOrigen")]
		public ISingleResult<Transferencias_SEL_ALL_BYCuentaIdOrigenResult> Transferencias_SEL_ALL_BYCuentaIdOrigen([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CuentaIdOrigen", DbType="Int")] System.Nullable<int> cuentaIdOrigen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cuentaIdOrigen);
			return ((ISingleResult<Transferencias_SEL_ALL_BYCuentaIdOrigenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Transferencias_SEL_ALL_BYUsuarioId")]
		public ISingleResult<Transferencias_SEL_ALL_BYUsuarioIdResult> Transferencias_SEL_ALL_BYUsuarioId([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioIdOrigen", DbType="Int")] System.Nullable<int> usuarioIdOrigen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioIdOrigen);
			return ((ISingleResult<Transferencias_SEL_ALL_BYUsuarioIdResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Transferencias_SEL_ALL_BYTransferenciaID")]
		public ISingleResult<Transferencias_SEL_ALL_BYTransferenciaIDResult> Transferencias_SEL_ALL_BYTransferenciaID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TransferenciaID", DbType="Int")] System.Nullable<int> transferenciaID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), transferenciaID);
			return ((ISingleResult<Transferencias_SEL_ALL_BYTransferenciaIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Transferencias_INS_NEW")]
		public int Transferencias_INS_NEW([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CuentaIdOrigen", DbType="Int")] System.Nullable<int> cuentaIdOrigen, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CuentaIdDestino", DbType="Int")] System.Nullable<int> cuentaIdDestino, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Monto", DbType="Decimal(18,0)")] System.Nullable<decimal> monto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="VarChar(1000)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="DateTime")] System.Nullable<System.DateTime> fecha)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cuentaIdOrigen, cuentaIdDestino, monto, descripcion, fecha);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Cuenta_SEL_ALL_BYCuentaID")]
		public ISingleResult<Cuenta_SEL_ALL_BYCuentaIDResult> Cuenta_SEL_ALL_BYCuentaID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CuentaID", DbType="Int")] System.Nullable<int> cuentaID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cuentaID);
			return ((ISingleResult<Cuenta_SEL_ALL_BYCuentaIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Cuentas_SEL_ALL_BYUSER")]
		public ISingleResult<Cuentas_SEL_ALL_BYUSERResult> Cuentas_SEL_ALL_BYUSER([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UsuarioID", DbType="Int")] System.Nullable<int> usuarioID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuarioID);
			return ((ISingleResult<Cuentas_SEL_ALL_BYUSERResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cuentas")]
	public partial class Cuenta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CuentaId;
		
		private int _TipoCuentaId;
		
		private decimal _Saldo;
		
		private int _UsuarioId;
		
		private EntitySet<Transferencia> _Transferencias;
		
		private EntitySet<Transferencia> _Transferencias1;
		
		private EntityRef<TipoCuenta> _TipoCuenta;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCuentaIdChanging(int value);
    partial void OnCuentaIdChanged();
    partial void OnTipoCuentaIdChanging(int value);
    partial void OnTipoCuentaIdChanged();
    partial void OnSaldoChanging(decimal value);
    partial void OnSaldoChanged();
    partial void OnUsuarioIdChanging(int value);
    partial void OnUsuarioIdChanged();
    #endregion
		
		public Cuenta()
		{
			this._Transferencias = new EntitySet<Transferencia>(new Action<Transferencia>(this.attach_Transferencias), new Action<Transferencia>(this.detach_Transferencias));
			this._Transferencias1 = new EntitySet<Transferencia>(new Action<Transferencia>(this.attach_Transferencias1), new Action<Transferencia>(this.detach_Transferencias1));
			this._TipoCuenta = default(EntityRef<TipoCuenta>);
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CuentaId
		{
			get
			{
				return this._CuentaId;
			}
			set
			{
				if ((this._CuentaId != value))
				{
					this.OnCuentaIdChanging(value);
					this.SendPropertyChanging();
					this._CuentaId = value;
					this.SendPropertyChanged("CuentaId");
					this.OnCuentaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCuentaId", DbType="Int NOT NULL")]
		public int TipoCuentaId
		{
			get
			{
				return this._TipoCuentaId;
			}
			set
			{
				if ((this._TipoCuentaId != value))
				{
					if (this._TipoCuenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTipoCuentaIdChanging(value);
					this.SendPropertyChanging();
					this._TipoCuentaId = value;
					this.SendPropertyChanged("TipoCuentaId");
					this.OnTipoCuentaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saldo", DbType="Decimal(18,0) NOT NULL")]
		public decimal Saldo
		{
			get
			{
				return this._Saldo;
			}
			set
			{
				if ((this._Saldo != value))
				{
					this.OnSaldoChanging(value);
					this.SendPropertyChanging();
					this._Saldo = value;
					this.SendPropertyChanged("Saldo");
					this.OnSaldoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioId", DbType="Int NOT NULL")]
		public int UsuarioId
		{
			get
			{
				return this._UsuarioId;
			}
			set
			{
				if ((this._UsuarioId != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUsuarioIdChanging(value);
					this.SendPropertyChanging();
					this._UsuarioId = value;
					this.SendPropertyChanged("UsuarioId");
					this.OnUsuarioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cuenta_Transferencia", Storage="_Transferencias", ThisKey="CuentaId", OtherKey="CuentaIdDestino")]
		public EntitySet<Transferencia> Transferencias
		{
			get
			{
				return this._Transferencias;
			}
			set
			{
				this._Transferencias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cuenta_Transferencia1", Storage="_Transferencias1", ThisKey="CuentaId", OtherKey="CuentaIdOrigen")]
		public EntitySet<Transferencia> Transferencias1
		{
			get
			{
				return this._Transferencias1;
			}
			set
			{
				this._Transferencias1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoCuenta_Cuenta", Storage="_TipoCuenta", ThisKey="TipoCuentaId", OtherKey="TipoCuentaId", IsForeignKey=true)]
		public TipoCuenta TipoCuenta
		{
			get
			{
				return this._TipoCuenta.Entity;
			}
			set
			{
				TipoCuenta previousValue = this._TipoCuenta.Entity;
				if (((previousValue != value) 
							|| (this._TipoCuenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoCuenta.Entity = null;
						previousValue.Cuentas.Remove(this);
					}
					this._TipoCuenta.Entity = value;
					if ((value != null))
					{
						value.Cuentas.Add(this);
						this._TipoCuentaId = value.TipoCuentaId;
					}
					else
					{
						this._TipoCuentaId = default(int);
					}
					this.SendPropertyChanged("TipoCuenta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Cuenta", Storage="_Usuario", ThisKey="UsuarioId", OtherKey="UsuarioId", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Cuentas.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Cuentas.Add(this);
						this._UsuarioId = value.UsuarioId;
					}
					else
					{
						this._UsuarioId = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Transferencias(Transferencia entity)
		{
			this.SendPropertyChanging();
			entity.Cuenta = this;
		}
		
		private void detach_Transferencias(Transferencia entity)
		{
			this.SendPropertyChanging();
			entity.Cuenta = null;
		}
		
		private void attach_Transferencias1(Transferencia entity)
		{
			this.SendPropertyChanging();
			entity.Cuenta1 = this;
		}
		
		private void detach_Transferencias1(Transferencia entity)
		{
			this.SendPropertyChanging();
			entity.Cuenta1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoCuenta")]
	public partial class TipoCuenta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TipoCuentaId;
		
		private string _Nombre;
		
		private EntitySet<Cuenta> _Cuentas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTipoCuentaIdChanging(int value);
    partial void OnTipoCuentaIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public TipoCuenta()
		{
			this._Cuentas = new EntitySet<Cuenta>(new Action<Cuenta>(this.attach_Cuentas), new Action<Cuenta>(this.detach_Cuentas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCuentaId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TipoCuentaId
		{
			get
			{
				return this._TipoCuentaId;
			}
			set
			{
				if ((this._TipoCuentaId != value))
				{
					this.OnTipoCuentaIdChanging(value);
					this.SendPropertyChanging();
					this._TipoCuentaId = value;
					this.SendPropertyChanged("TipoCuentaId");
					this.OnTipoCuentaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoCuenta_Cuenta", Storage="_Cuentas", ThisKey="TipoCuentaId", OtherKey="TipoCuentaId")]
		public EntitySet<Cuenta> Cuentas
		{
			get
			{
				return this._Cuentas;
			}
			set
			{
				this._Cuentas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cuentas(Cuenta entity)
		{
			this.SendPropertyChanging();
			entity.TipoCuenta = this;
		}
		
		private void detach_Cuentas(Cuenta entity)
		{
			this.SendPropertyChanging();
			entity.TipoCuenta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transferencias")]
	public partial class Transferencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TransferenciaId;
		
		private int _CuentaIdOrigen;
		
		private int _CuentaIdDestino;
		
		private decimal _Monto;
		
		private string _Descripcion;
		
		private System.DateTime _Fecha;
		
		private EntityRef<Cuenta> _Cuenta;
		
		private EntityRef<Cuenta> _Cuenta1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTransferenciaIdChanging(int value);
    partial void OnTransferenciaIdChanged();
    partial void OnCuentaIdOrigenChanging(int value);
    partial void OnCuentaIdOrigenChanged();
    partial void OnCuentaIdDestinoChanging(int value);
    partial void OnCuentaIdDestinoChanged();
    partial void OnMontoChanging(decimal value);
    partial void OnMontoChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    #endregion
		
		public Transferencia()
		{
			this._Cuenta = default(EntityRef<Cuenta>);
			this._Cuenta1 = default(EntityRef<Cuenta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransferenciaId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int TransferenciaId
		{
			get
			{
				return this._TransferenciaId;
			}
			set
			{
				if ((this._TransferenciaId != value))
				{
					this.OnTransferenciaIdChanging(value);
					this.SendPropertyChanging();
					this._TransferenciaId = value;
					this.SendPropertyChanged("TransferenciaId");
					this.OnTransferenciaIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaIdOrigen", DbType="Int NOT NULL")]
		public int CuentaIdOrigen
		{
			get
			{
				return this._CuentaIdOrigen;
			}
			set
			{
				if ((this._CuentaIdOrigen != value))
				{
					if (this._Cuenta1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCuentaIdOrigenChanging(value);
					this.SendPropertyChanging();
					this._CuentaIdOrigen = value;
					this.SendPropertyChanged("CuentaIdOrigen");
					this.OnCuentaIdOrigenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaIdDestino", DbType="Int NOT NULL")]
		public int CuentaIdDestino
		{
			get
			{
				return this._CuentaIdDestino;
			}
			set
			{
				if ((this._CuentaIdDestino != value))
				{
					if (this._Cuenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCuentaIdDestinoChanging(value);
					this.SendPropertyChanging();
					this._CuentaIdDestino = value;
					this.SendPropertyChanged("CuentaIdDestino");
					this.OnCuentaIdDestinoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Decimal(18,0) NOT NULL")]
		public decimal Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this.OnMontoChanging(value);
					this.SendPropertyChanging();
					this._Monto = value;
					this.SendPropertyChanged("Monto");
					this.OnMontoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cuenta_Transferencia", Storage="_Cuenta", ThisKey="CuentaIdDestino", OtherKey="CuentaId", IsForeignKey=true)]
		public Cuenta Cuenta
		{
			get
			{
				return this._Cuenta.Entity;
			}
			set
			{
				Cuenta previousValue = this._Cuenta.Entity;
				if (((previousValue != value) 
							|| (this._Cuenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cuenta.Entity = null;
						previousValue.Transferencias.Remove(this);
					}
					this._Cuenta.Entity = value;
					if ((value != null))
					{
						value.Transferencias.Add(this);
						this._CuentaIdDestino = value.CuentaId;
					}
					else
					{
						this._CuentaIdDestino = default(int);
					}
					this.SendPropertyChanged("Cuenta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cuenta_Transferencia1", Storage="_Cuenta1", ThisKey="CuentaIdOrigen", OtherKey="CuentaId", IsForeignKey=true)]
		public Cuenta Cuenta1
		{
			get
			{
				return this._Cuenta1.Entity;
			}
			set
			{
				Cuenta previousValue = this._Cuenta1.Entity;
				if (((previousValue != value) 
							|| (this._Cuenta1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cuenta1.Entity = null;
						previousValue.Transferencias1.Remove(this);
					}
					this._Cuenta1.Entity = value;
					if ((value != null))
					{
						value.Transferencias1.Add(this);
						this._CuentaIdOrigen = value.CuentaId;
					}
					else
					{
						this._CuentaIdOrigen = default(int);
					}
					this.SendPropertyChanged("Cuenta1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UsuarioId;
		
		private string _Nombre;
		
		private EntitySet<Cuenta> _Cuentas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsuarioIdChanging(int value);
    partial void OnUsuarioIdChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Usuario()
		{
			this._Cuentas = new EntitySet<Cuenta>(new Action<Cuenta>(this.attach_Cuentas), new Action<Cuenta>(this.detach_Cuentas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UsuarioId
		{
			get
			{
				return this._UsuarioId;
			}
			set
			{
				if ((this._UsuarioId != value))
				{
					this.OnUsuarioIdChanging(value);
					this.SendPropertyChanging();
					this._UsuarioId = value;
					this.SendPropertyChanged("UsuarioId");
					this.OnUsuarioIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Cuenta", Storage="_Cuentas", ThisKey="UsuarioId", OtherKey="UsuarioId")]
		public EntitySet<Cuenta> Cuentas
		{
			get
			{
				return this._Cuentas;
			}
			set
			{
				this._Cuentas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Cuentas(Cuenta entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Cuentas(Cuenta entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	public partial class Transferencias_SEL_ALL_BYCuentaIdOrigenResult
	{
		
		private int _TransferenciaId;
		
		private int _CuentaIdOrigen;
		
		private int _CuentaIdDestino;
		
		private decimal _Monto;
		
		private string _Descripcion;
		
		private System.DateTime _Fecha;
		
		public Transferencias_SEL_ALL_BYCuentaIdOrigenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransferenciaId", DbType="Int NOT NULL")]
		public int TransferenciaId
		{
			get
			{
				return this._TransferenciaId;
			}
			set
			{
				if ((this._TransferenciaId != value))
				{
					this._TransferenciaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaIdOrigen", DbType="Int NOT NULL")]
		public int CuentaIdOrigen
		{
			get
			{
				return this._CuentaIdOrigen;
			}
			set
			{
				if ((this._CuentaIdOrigen != value))
				{
					this._CuentaIdOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaIdDestino", DbType="Int NOT NULL")]
		public int CuentaIdDestino
		{
			get
			{
				return this._CuentaIdDestino;
			}
			set
			{
				if ((this._CuentaIdDestino != value))
				{
					this._CuentaIdDestino = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Decimal(18,0) NOT NULL")]
		public decimal Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this._Monto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
	}
	
	public partial class Transferencias_SEL_ALL_BYUsuarioIdResult
	{
		
		private int _TransferenciaId;
		
		private int _CuentaIdOrigen;
		
		private int _CuentaIdDestino;
		
		private decimal _Monto;
		
		private string _Descripcion;
		
		private System.DateTime _Fecha;
		
		private int _CuentaId;
		
		private int _TipoCuentaId;
		
		private decimal _Saldo;
		
		private int _UsuarioId;
		
		public Transferencias_SEL_ALL_BYUsuarioIdResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransferenciaId", DbType="Int NOT NULL")]
		public int TransferenciaId
		{
			get
			{
				return this._TransferenciaId;
			}
			set
			{
				if ((this._TransferenciaId != value))
				{
					this._TransferenciaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaIdOrigen", DbType="Int NOT NULL")]
		public int CuentaIdOrigen
		{
			get
			{
				return this._CuentaIdOrigen;
			}
			set
			{
				if ((this._CuentaIdOrigen != value))
				{
					this._CuentaIdOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaIdDestino", DbType="Int NOT NULL")]
		public int CuentaIdDestino
		{
			get
			{
				return this._CuentaIdDestino;
			}
			set
			{
				if ((this._CuentaIdDestino != value))
				{
					this._CuentaIdDestino = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Decimal(18,0) NOT NULL")]
		public decimal Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this._Monto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaId", DbType="Int NOT NULL")]
		public int CuentaId
		{
			get
			{
				return this._CuentaId;
			}
			set
			{
				if ((this._CuentaId != value))
				{
					this._CuentaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCuentaId", DbType="Int NOT NULL")]
		public int TipoCuentaId
		{
			get
			{
				return this._TipoCuentaId;
			}
			set
			{
				if ((this._TipoCuentaId != value))
				{
					this._TipoCuentaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saldo", DbType="Decimal(18,0) NOT NULL")]
		public decimal Saldo
		{
			get
			{
				return this._Saldo;
			}
			set
			{
				if ((this._Saldo != value))
				{
					this._Saldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioId", DbType="Int NOT NULL")]
		public int UsuarioId
		{
			get
			{
				return this._UsuarioId;
			}
			set
			{
				if ((this._UsuarioId != value))
				{
					this._UsuarioId = value;
				}
			}
		}
	}
	
	public partial class Transferencias_SEL_ALL_BYTransferenciaIDResult
	{
		
		private int _TransferenciaId;
		
		private int _CuentaIdOrigen;
		
		private int _CuentaIdDestino;
		
		private decimal _Monto;
		
		private string _Descripcion;
		
		private System.DateTime _Fecha;
		
		public Transferencias_SEL_ALL_BYTransferenciaIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransferenciaId", DbType="Int NOT NULL")]
		public int TransferenciaId
		{
			get
			{
				return this._TransferenciaId;
			}
			set
			{
				if ((this._TransferenciaId != value))
				{
					this._TransferenciaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaIdOrigen", DbType="Int NOT NULL")]
		public int CuentaIdOrigen
		{
			get
			{
				return this._CuentaIdOrigen;
			}
			set
			{
				if ((this._CuentaIdOrigen != value))
				{
					this._CuentaIdOrigen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaIdDestino", DbType="Int NOT NULL")]
		public int CuentaIdDestino
		{
			get
			{
				return this._CuentaIdDestino;
			}
			set
			{
				if ((this._CuentaIdDestino != value))
				{
					this._CuentaIdDestino = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Monto", DbType="Decimal(18,0) NOT NULL")]
		public decimal Monto
		{
			get
			{
				return this._Monto;
			}
			set
			{
				if ((this._Monto != value))
				{
					this._Monto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
	}
	
	public partial class Cuenta_SEL_ALL_BYCuentaIDResult
	{
		
		private int _CuentaId;
		
		private int _TipoCuentaId;
		
		private decimal _Saldo;
		
		private int _UsuarioId;
		
		private string _TipoCuenta;
		
		public Cuenta_SEL_ALL_BYCuentaIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaId", DbType="Int NOT NULL")]
		public int CuentaId
		{
			get
			{
				return this._CuentaId;
			}
			set
			{
				if ((this._CuentaId != value))
				{
					this._CuentaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCuentaId", DbType="Int NOT NULL")]
		public int TipoCuentaId
		{
			get
			{
				return this._TipoCuentaId;
			}
			set
			{
				if ((this._TipoCuentaId != value))
				{
					this._TipoCuentaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saldo", DbType="Decimal(18,0) NOT NULL")]
		public decimal Saldo
		{
			get
			{
				return this._Saldo;
			}
			set
			{
				if ((this._Saldo != value))
				{
					this._Saldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioId", DbType="Int NOT NULL")]
		public int UsuarioId
		{
			get
			{
				return this._UsuarioId;
			}
			set
			{
				if ((this._UsuarioId != value))
				{
					this._UsuarioId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCuenta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TipoCuenta
		{
			get
			{
				return this._TipoCuenta;
			}
			set
			{
				if ((this._TipoCuenta != value))
				{
					this._TipoCuenta = value;
				}
			}
		}
	}
	
	public partial class Cuentas_SEL_ALL_BYUSERResult
	{
		
		private int _CuentaId;
		
		private int _TipoCuentaId;
		
		private decimal _Saldo;
		
		private int _UsuarioId;
		
		private string _TipoCuenta;
		
		public Cuentas_SEL_ALL_BYUSERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuentaId", DbType="Int NOT NULL")]
		public int CuentaId
		{
			get
			{
				return this._CuentaId;
			}
			set
			{
				if ((this._CuentaId != value))
				{
					this._CuentaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCuentaId", DbType="Int NOT NULL")]
		public int TipoCuentaId
		{
			get
			{
				return this._TipoCuentaId;
			}
			set
			{
				if ((this._TipoCuentaId != value))
				{
					this._TipoCuentaId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saldo", DbType="Decimal(18,0) NOT NULL")]
		public decimal Saldo
		{
			get
			{
				return this._Saldo;
			}
			set
			{
				if ((this._Saldo != value))
				{
					this._Saldo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioId", DbType="Int NOT NULL")]
		public int UsuarioId
		{
			get
			{
				return this._UsuarioId;
			}
			set
			{
				if ((this._UsuarioId != value))
				{
					this._UsuarioId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoCuenta", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TipoCuenta
		{
			get
			{
				return this._TipoCuenta;
			}
			set
			{
				if ((this._TipoCuenta != value))
				{
					this._TipoCuenta = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
